### ISSUE TITLE
Permission denied: connect to geckodriver

### ISSUE THREAD

**Issue by q-jack** [lmc-eu/steward#169]
I am using selenium standalone server 3.7.1 and the geckodriver 0.19.1 on my windows pc.
When trying to start a test
`>steward run staging firefox --pattern CreateStudyTest.php --filter testCreateStudy -vvv`
I get this error log

> My\CreateStudyTest> Fatal error: Uncaught Facebook\WebDriver\Exception\UnknownServerException: Permission denied: connect in C:\xampp\htdocs\portal\app\webroot\selenium-tests\vendor\facebook\webdriver\lib\Exception\WebDriverException.php:114
My\CreateStudyTest> Stack trace:
My\CreateStudyTest> #0 C:\xampp\htdocs\portal\app\webroot\selenium-tests\vendor\facebook\webdriver\lib\Remote\HttpCommandExecutor.php(320): Facebook\WebDriver\Exception\WebDriverException::throwException(13, 'Permission deni...', Array)
My\CreateStudyTest> #1 C:\xampp\htdocs\portal\app\webroot\selenium-tests\vendor\facebook\webdriver\lib\Remote\RemoteWebDriver.php(126): Facebook\WebDriver\Remote\HttpCommandExecutor->execute(Object(Facebook\WebDriver\Remote\WebDriverCommand))
My\CreateStudyTest> #2 C:\xampp\htdocs\portal\app\webroot\selenium-tests\vendor\lmc\steward\src\Listener\WebDriverListener.php(175): Facebook\WebDriver\Remote\RemoteWebDriver::create('http://localhos...', Object(Facebook\WebDriver\Remote\DesiredCapabilities), 120000, 3600000, NULL, NULL, Object(Facebook\WebDriver\Remote\DesiredCapabilities))
My\CreateStudyTest> #3 C:\xampp\htdocs\portal\app\webroot\ in C:\xampp\htdocs\portal\app\webroot\selenium-tests\vendor\facebook\webdriver\lib\Exception\WebDriverException.php on line 114
My\CreateStudyTest>
My\CreateStudyTest ERR> PHP Fatal error:  Uncaught Facebook\WebDriver\Exception\UnknownServerException: Permission denied: connect in C:\xampp\htdocs\portal\app\webroot\selenium-tests\vendor\facebook\webdriver\lib\Exception\WebDriverException.php:114
My\CreateStudyTest ERR> Stack trace:
My\CreateStudyTest ERR> #0 C:\xampp\htdocs\portal\app\webroot\selenium-tests\vendor\facebook\webdriver\lib\Remote\HttpCommandExecutor.php(320): Facebook\WebDriver\Exception\WebDriverException::throwException(13, 'Permission deni...', Array)
My\CreateStudyTest ERR> #1 C:\xampp\htdocs\portal\app\webroot\selenium-tests\vendor\facebook\webdriver\lib\Remote\RemoteWebDriver.php(126): Facebook\WebDriver\Remote\HttpCommandExecutor->execute(Object(Facebook\WebDriver\Remote\WebDriverCommand))
My\CreateStudyTest ERR> #2 C:\xampp\htdocs\portal\app\webroot\selenium-tests\vendor\lmc\steward\src\Listener\WebDriverListener.php(175): Facebook\WebDriver\Remote\RemoteWebDriver::create('http://localhos...', Object(Facebook\WebDriver\Remote\DesiredCapabilities), 120000, 3600000, NULL, NULL, Object(Facebook\WebDriver\Remote\DesiredCapabilities))
My\CreateStudyTest ERR> #3 C:\xampp\htdocs\portal\app\webroot\ in C:\xampp\htdocs\portal\app\webroot\selenium-tests\vendor\facebook\webdriver\lib\Exception\WebDriverException.php on line 114
[2017-11-23 11:48:06] Finished execution of testcase "My\CreateStudyTest" (result: fatal, time: 0.9 sec)
[2017-11-23 11:48:06] Waiting (running: 0, queued: 0, done: 1 [fatal: 1])
[2017-11-23 11:48:06] All testcases done in 1.3 seconds

 [ERROR] Testcases executed: 1 (fatal: 1)

And the server logs
`C:\xampp\htdocs\portal\app\webroot\selenium-tests\vendor\bin>java -jar selenium-server-standalone-3.7.1.jar -enablePassThrough false
11:47:48.699 INFO - Selenium build info: version: '3.7.1', revision: '8a0099a'
11:47:48.699 INFO - Launching a standalone Selenium Server
2017-11-23 11:47:48.714:INFO::main: Logging initialized @308ms to org.seleniumhq.jetty9.util.log.StdErrLog
11:47:48.777 INFO - Driver class not found: com.opera.core.systems.OperaDriver
11:47:48.815 INFO - Driver provider class org.openqa.selenium.safari.SafariDriver registration is skipped:
 registration capabilities Capabilities {browserName: safari, platform: MAC, version: } does not match the current platform WIN10
2017-11-23 11:47:48.877:INFO:osjs.Server:main: jetty-9.4.5.v20170502
2017-11-23 11:47:48.899:WARN:osjs.SecurityHandler:main: ServletContext@o.s.j.s.ServletContextHandler@2bbf4b8b{/,null,STARTING} has uncovered http methods for path: /
2017-11-23 11:47:48.899:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@2bbf4b8b{/,null,AVAILABLE}
2017-11-23 11:47:49.295:INFO:osjs.AbstractConnector:main: Started ServerConnector@6141ea3d{HTTP/1.1,[http/1.1]}{0.0.0.0:4444}
2017-11-23 11:47:49.296:INFO:osjs.Server:main: Started @880ms
11:47:49.296 INFO - Selenium Server is up and running
11:48:06.019 INFO - Executing: [new session: Capabilities {browserName: firefox, firefox_profile: UEsDBBQAAAAAAAJed0uBK46tKgA..., name: My\CreateStudyTest::testCre..., platform: ANY, requiredCapabilities: []}])
11:48:06.051 INFO - Creating a new session for Capabilities {browserName: firefox, firefox_profile: UEsDBBQAAAAAAAJed0uBK46tKgA..., name: My\CreateStudyTest::testCre..., platform: ANY, requiredCapabilities: []}
11:48:06.547 WARN - Exception thrown
org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:07:36.161Z'
System info: host: 'me', ip: '192.168.188.33', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: unknown
        at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:116)
        at org.openqa.selenium.remote.server.DefaultDriverProvider.newInstance(DefaultDriverProvider.java:102)
        at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:87)
        at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:171)
        at org.openqa.selenium.remote.server.DefaultSession.<init>(DefaultSession.java:88)
        at org.openqa.selenium.remote.server.DefaultSession.createSession(DefaultSession.java:76)
        at org.openqa.selenium.remote.server.DefaultDriverSessions.newSession(DefaultDriverSessions.java:72)
        at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:63)
        at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:37)
        at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:112)
        at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:192)
        at org.openqa.selenium.remote.server.DriverServlet.lambda$handleRequest$0(DriverServlet.java:261)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:108)
        ... 16 more
Caused by: org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:07:36.161Z'
System info: host: 'me', ip: '192.168.188.33', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: FirefoxDriver
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:621)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:219)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:142)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:106)
        ... 21 more
Caused by: java.lang.RuntimeException: java.net.SocketException: Permission denied: connect
        at org.openqa.selenium.net.PortProber.waitForPortUp(PortProber.java:160)
        at org.openqa.selenium.firefox.GeckoDriverService.waitUntilAvailable(GeckoDriverService.java:97)
        at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:178)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:79)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:600)
        ... 25 more
Caused by: java.net.SocketException: Permission denied: connect
        at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at org.openqa.selenium.net.PortProber.waitForPortUp(PortProber.java:152)
        ... 29 more
11:48:06.563 WARN - Exception: Permission denied: connect
1511434086979   geckodriver     INFO    geckodriver 0.19.1
1511434087016   geckodriver     INFO    Listening on 127.0.0.1:5016`

The geckodriver is located inside the same folder as the standalone server.
Firefox is up to date.

**Comment by q-jack** [comment]
I belive the port was blocked by chrome

**Comment by OndraM** [comment]
Hi @q-jack , this does not look like Steward issue, more probably something with geckodriver itself.

You may also try latest Selenium server (3.8.1) or try running it in Docker image - see https://github.com/lmc-eu/steward/wiki/Selenium-server-&-browser-drivers#option-2-start-selenium-server--browser-inside-docker-
