### ISSUE TITLE
php-webdriver sendKeys() function is not working with geckodriver

### ISSUE THREAD

**Issue by y123sing** [lmc-eu/steward#203]
Here is the description:

**System**

OS: Win 10 ( 32 Bit )
Selenium Version: 3.8.1, geckodriver-v0.20.0, Java1.8.0_162
Browser: FireFox 59.0

**Testcase**

Expected Behavior - sendKeys() function should work to enter keys
Actual Behavior - The script failed with below exceptions

**Stacktrace**

My\TitlePageTest> 1) My\TitlePageTest::testShouldContainSearchInput
**My\TitlePageTest> Facebook\WebDriver\Exception\UnknownCommandException: sendKeysToActiveElement**
My\TitlePageTest> Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T19:05:32.194Z'
My\TitlePageTest> System info: host: 'XXXXXX', ip: 'XXXXXX', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_144'
My\TitlePageTest> Driver info: driver.version: RemoteWebDriver
My\TitlePageTest>
My\TitlePageTest> C:\Users\abc\Desktop\steward\vendor\facebook\webdriver\lib\Exception\WebDriverException.php:106
My\TitlePageTest> C:\Users\abc\Desktop\steward\vendor\facebook\webdriver\lib\Remote\HttpCommandExecutor.php:320
My\TitlePageTest> C:\Users\abc\Desktop\steward\vendor\facebook\webdriver\lib\Remote\RemoteWebDriver.php:535
My\TitlePageTest> C:\Users\abc\Desktop\steward\vendor\lmc\steward\src\WebDriver\RemoteWebDriver.php:29
My\TitlePageTest> C:\Users\abc\Desktop\steward\vendor\facebook\webdriver\lib\Remote\RemoteExecuteMethod.php:40
My\TitlePageTest> C:\Users\abc\Desktop\steward\vendor\facebook\webdriver\lib\Remote\RemoteKeyboard.php:47
My\TitlePageTest> C:\Users\abc\Desktop\steward\tests\TitlePageTest.php:37
My\TitlePageTest>
My\TitlePageTest> ERRORS!
My\TitlePageTest> Tests: 1, Assertions: 1, Errors: 1.
My\TitlePageTest>
[2018-03-22 11:52:57] Finished execution of testcase "My\TitlePageTest" (result: failed, time: 17.0 sec)
[2018-03-22 11:52:57] Waiting (running: 0, queued: 0, done: 1 [failed: 1])
[2018-03-22 11:52:57] All testcases done in 17.2 seconds

**Selenium Console Output**

16:22:55.295 INFO - Executing: [send keys to active: [php-webdriver]])
16:22:55.295 WARN - Exception thrown
org.openqa.selenium.UnsupportedCommandException: sendKeysToActiveElement
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T19:05:32.194Z'
System info: host: 'HECTOR-AUTO5', ip: '172.16.136.216', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_144'
Driver info: driver.version: RemoteWebDriver
        at org.openqa.selenium.remote.http.AbstractHttpCommandCodec.encode(AbstractHttpCommandCodec.java:219)
        at org.openqa.selenium.remote.http.AbstractHttpCommandCodec.encode(AbstractHttpCommandCodec.java:118)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
        at org.openqa.selenium.remote.RemoteExecuteMethod.execute(RemoteExecuteMethod.java:35)
        at org.openqa.selenium.remote.RemoteKeyboard.sendKeys(RemoteKeyboard.java:38)
        at org.openqa.selenium.support.events.internal.EventFiringKeyboard.sendKeys(EventFiringKeyboard.java:41)
        at org.openqa.selenium.remote.server.handler.interactions.SendKeyToActiveElement.call(SendKeyToActiveElement.java:56)
        at org.openqa.selenium.remote.server.handler.interactions.SendKeyToActiveElement.call(SendKeyToActiveElement.java:31)
        at org.openqa.selenium.remote.server.handler.WebDriverHandler.handle(WebDriverHandler.java:41)
        at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:112)
        at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:191)
        at org.openqa.selenium.remote.server.DriverServlet.lambda$handleRequest$0(DriverServlet.java:261)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
16:22:55.296 WARN - Exception: sendKeysToActiveElement
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T19:05:32.194Z'
System info: host: 'HECTOR-AUTO5', ip: '172.16.136.216', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_144'
Driver info: driver.version: RemoteWebDriver

**Comment by OndraM** [comment]
Hi, GeckoDrivers are not yet supported by the [underlying library php-webdriver](https://github.com/facebook/php-webdriver/), which takes care of communicating with Selenium . See issue https://github.com/facebook/php-webdriver/issues/469 in the library for more information.
