### ISSUE TITLE
Edge Web driver doesn't work as intended

### ISSUE THREAD

**Issue by ShabariRepo** [lmc-eu/steward#228]
- basically need to get edge working with php tests and selenium 3 (phpunit & etc)
- wanted to start with steward since I like the structure of tests
- Chrome and Firefox works out of the box like a charm, but edge is a pain
- P.S.:  I know.. Edge and IE are a pain.. but clients for w.e reason use Edge  o_o
- really appreciate the hand guys & gals :)

Edge Web Driver version:  Release 17134
Selenium version:  selenium-server-standalone-3.14.0
lmc/steward version:  2.3

java -Dwebdriver.edge.driver="/path/to/selenium/drivers/MicrosoftWebDriver.exe" -jar ./vendor/bin/selenium-server-standalone-3.14.0.jar

Command run: ./vendor/bin/steward run stating microsoftedge

this works:
./vendor/bin/steward run stating chrome
./vendor/bin/steward run stating firefox

Running the basic test here from the README.md

```
<?php
// selenium-tests/tests/TitlePageTest.php

namespace My; // Note the "My" namespace maps to the "tests" folder, as defined in the autoload part of `composer.json`.

use Facebook\WebDriver\WebDriverBy;
use Lmc\Steward\Test\AbstractTestCase;

class TitlePageTest extends AbstractTestCase
{
    public function testShouldContainSearchInput()
    {
        // Load the URL (will wait until page is loaded)
        $this->wd->get('http://www.w3.org/'); // $this->wd holds instance of \RemoteWebDriver

        // Do some assertion
        $this->assertContains('W3C', $this->wd->getTitle());

        // You can use $this->log(), $this->warn() or $this->debug() with sprintf-like syntax
        $this->log('Current page "%s" has title "%s"', $this->wd->getCurrentURL(), $this->wd->getTitle());

        // Make sure search input is present
        $searchInput = $this->wd->findElement(WebDriverBy::cssSelector('#search-form input'));
        // Or you can use syntax sugar provided by Steward (this is equivalent of previous line)
        $searchInput = $this->findByCss('#search-form input');

        // Assert title of the search input
        $this->assertEquals('Search', $searchInput->getAttribute('title'));
    }
}
```

Console Output:
13:02:35.400 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "browserName": "MicrosoftEdge",
  "name": "My\\TitlePageTest::testShouldContainSearchInput",
  "requiredCapabilities": [
  ]
}
13:02:35.400 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.edge.EdgeDriverService)

Other Console Output (running non lmc/steward tests):
1) GitHubSearchTest::testGitHub
Facebook\WebDriver\Exception\SessionNotCreatedException: Unable to create new service: EdgeDriverService
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:13:22.693Z'
System info: host: 'A1011701', ip: '192.168.50.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: driver.version: unknown

**Comment by ShabariRepo** [comment]
If i didnt mention, im super new to php testing
- just somewhat familiar with the language
- to give some context im from a dotnet / java or JS background

**Comment by OndraM** [comment]
Hi,
could you please run steward with `-vvv` and post here full output? Like `steward run env browser -vvv`

Similarly, you can run selenium server with `-debug` param to see more verbose information.

**Comment by ShabariRepo** [comment]
Hey @OndraM  thanks for the reply i ran what you asked
- I had done some more digging and found that php webdriver works with Edge only when its running as a separate node (not sure if this has something to do with it) 
- regardless here is the output

```
Browser: MicrosoftEdge
Environment: staging
Base path to fixtures results: C:\git\pfa_clone2\PFA\selenium-automation\selenium-tests\tests
Path to logs: C:\git\pfa_clone2\PFA\selenium-automation\selenium-tests\logs
Ignore delays: no
Selenium server (hub) url: http://localhost:4444, trying connection...OK (browserstack cloud service detected)
Searching for testcases:
 - in directory "C:\git\pfa_clone2\PFA\selenium-automation\selenium-tests\tests"
 - by pattern "*Test.php"
Found testcase file #1: C:\git\pfa_clone2\PFA\selenium-automation\selenium-tests\tests\TitlePageTest.php
Testcase "My\TitlePageTest" is prepared to be run

Starting execution of testcases
-------------------------------
[2018-11-05 20:49:46] Execution of testcase "My\TitlePageTest" started with command:
C:\xampp\php\php.exe C:\git\pfa_clone2\PFA\selenium-automation\selenium-tests\vendor\lmc\steward\bin\phpunit-steward "--log-junit=C:\git\pfa_clone2\PFA\selenium-automation\selenium-tests\logs/My-TitlePageTest.xml" --configuration=C:\git\pfa_clone2\PFA\selenium-automation\selenium-tests\vendor\lmc\steward\src\phpunit.xml --colors=always C:\git\pfa_clone2\PFA\selenium-automation\selenium-tests\tests\TitlePageTest.php
[2018-11-05 20:49:46] Waiting (running: 1, queued: 0, done: 0)
My\TitlePageTest> [2018-11-05 20:49:46]: Registering test results publisher "Lmc\Steward\Publisher\XmlPublisher"
My\TitlePageTest>
My\TitlePageTest> PHPUnit 5.7.27 by Sebastian Bergmann and contributors.
My\TitlePageTest>
My\TitlePageTest> [2018-11-05 20:49:46]: Initializing "MicrosoftEdge" WebDriver for "My\TitlePageTest::testShouldContainSearchInput"
My\TitlePageTest>
My\TitlePageTest ERR> PHP Fatal error:  Uncaught Facebook\WebDriver\Exception\SessionNotCre
My\TitlePageTest>
My\TitlePageTest> Fatal error: Uncaught Facebook\WebDriver\Exception\SessionNotCreatedException: Unable to create new service: EdgeDriverService
My\TitlePageTest> Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:13:22.693Z'My\TitlePageTest> System info: host: 'A1011701', ip: '192.168.50.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
My\TitlePageTest> Driver info: driver.version: unknown in C:\git\pfa_clone2\PFA\selenium-automation\selenium-tests\vendor\facebook\webdriver\lib\Exception\WebDriverException.php:154
My\TitlePageTest> Stack trace:
My\TitlePageTest> #0 C:\git\pfa_clone2\PFA\selenium-automation\selenium-tests\vendor\facebook\webdriver\lib\Remote\HttpCommandExecutor.php(326): Facebook\WebDriver\Exception\WebDriverException::throwException(33, 'Unable to creat...', Array)
My\TitlePageTest> #1 C:\git\pfa_clone2\PFA\selenium-automation\selenium-tests\vendor\facebook\webdriver\lib\Remote\RemoteWebDriver.php(126): Facebook\WebDriver\Remote\HttpCommandExecutor->execute(Object(Facebook\WebDriver\Remote\WebDriverCommand))
My\TitlePageTest> #2 C:\git\pfa_clone2\PFA\selenium-automation\selenium-t in C:\git\pfa_clone2\PFA\selenium-automation\selenium-tests\vendor\facebook\webdriver\lib\Exception\WebDriverException.php on line 154
My\TitlePageTest>
My\TitlePageTest ERR> atedException: Unable to create new service: EdgeDriverService
My\TitlePageTest ERR> Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:13:22.693Z'
My\TitlePageTest ERR> System info: host: 'A1011701', ip: '192.168.50.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
My\TitlePageTest ERR> Driver info: driver.version: unknown in C:\git\pfa_clone2\PFA\selenium-automation\selenium-tests\vendor\facebook\webdriver\lib\Exception\WebDriverException.php:154
My\TitlePageTest ERR> Stack trace:
My\TitlePageTest ERR> #0 C:\git\pfa_clone2\PFA\selenium-automation\selenium-tests\vendor\facebook\webdriver\lib\Remote\HttpCommandExecutor.php(326): Facebook\WebDriver\Exception\WebDriverException::throwException(33, 'Unable to creat...', Array)
My\TitlePageTest ERR> #1 C:\git\pfa_clone2\PFA\selenium-automation\selenium-tests\vendor\facebook\webdriver\lib\Remote\RemoteWebDriver.php(126): Facebook\WebDriver\Remote\HttpCommandExecutor->execute(Object(Facebook\WebDriver\Remote\WebDriverCommand))
My\TitlePageTest ERR> #2 C:\git\pfa_clone2\PFA\selenium-automation\selenium-t in C:\git\pfa_clone2\PFA\selenium-automation\selenium-tests\vendor\facebook\webdriver\lib\Exception\WebDriverException.php on line 154
[2018-11-05 20:49:46] Finished execution of testcase "My\TitlePageTest" (result: fatal, time: 0.5 sec)
[2018-11-05 20:49:46] Waiting (running: 0, queued: 0, done: 1 [fatal: 1])
[2018-11-05 20:49:46] All testcases done in 0.7 seconds
```

Also, here is the webdriver with selenium started

![image](https://user-images.githubusercontent.com/10635357/48023567-33d11e00-e10c-11e8-81fd-281870efd09f.png)

**Comment by OndraM** [comment]
>  php webdriver works with Edge only when its running as a separate node

This is currently a "feature". Steward, respectively the underlying php-webdriver library cannot currently directly communicate with EdgeDriver. The connection must now be retranslated via Selenium server.

For now I recommend using Chrome and ChromeDriver (which will be started by Selenium server). See https://github.com/lmc-eu/steward/wiki/Selenium-server-&-browser-drivers 
The underlying php-webdriver library may currently not be working properly with Edge (this will hopefully change in near future).

So I understand it now works for you, right?
